package caddy

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"lns/internal/config"
	"lns/internal/devruntime"
	"lns/internal/models"
	"lns/internal/registry"
	"lns/internal/state"
)

type UpstreamMode int

const (
	UpstreamModeHost UpstreamMode = iota
	UpstreamModeDockerNetwork
)

func GenerateServiceBlock(project *models.Project, service *models.Service, httpPort int, upstreamMode UpstreamMode) string {
	return generateServiceBlock(project, service, httpPort, true, upstreamMode)
}

func generateServiceBlock(project *models.Project, service *models.Service, proxyPort int, https bool, upstreamMode UpstreamMode) string {
	hostname := project.GetServiceHostname(*service)
	upstream := getUpstream(service, upstreamMode)
	scheme := "http"
	if https {
		scheme = "https"
	}

	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("%s://%s:%d {\n", scheme, hostname, proxyPort))
	if https {
		sb.WriteString("\ttls internal\n")
	}

	if service.EffectiveProfile() == models.ProfileHMR {
		sb.WriteString(fmt.Sprintf("\treverse_proxy %s {\n", upstream))
		sb.WriteString("\t\theader_up Host {host}\n")
		sb.WriteString("\t\theader_up X-Real-IP {remote_host}\n")
		sb.WriteString("\t}\n")
	} else {
		sb.WriteString(fmt.Sprintf("\treverse_proxy %s\n", upstream))
	}

	sb.WriteString("}")

	return sb.String()
}

func GenerateProjectCaddyfile(project *models.Project, httpPort int, upstreamMode UpstreamMode) string {
	return generateProjectCaddyfile(project, httpPort, true, upstreamMode)
}

func generateProjectCaddyfile(project *models.Project, proxyPort int, https bool, upstreamMode UpstreamMode) string {
	if len(project.Services) == 0 {
		return fmt.Sprintf("# Project: %s (no services configured)\n", project.Name)
	}

	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Project: %s\n", project.Name))
	if project.Path != "" {
		sb.WriteString(fmt.Sprintf("# Path: %s\n", project.Path))
	}
	sb.WriteString("\n")

	for i := range project.Services {
		if project.Services[i].Port == 0 && upstreamMode == UpstreamModeHost {
			continue
		}
		sb.WriteString(generateServiceBlock(project, &project.Services[i], proxyPort, https, upstreamMode))
		sb.WriteString("\n\n")
	}

	return sb.String()
}

func GenerateGlobalCaddyfile(httpPort int, adminAddr string) string {
	return generateGlobalCaddyfile(httpPort, adminAddr, true)
}

func generateGlobalCaddyfile(proxyPort int, adminAddr string, https bool) string {
	caddyConfigDir := config.GetCaddyConfigDir()
	globalPath := config.GetGlobalCaddyfilePath()
	portOption := fmt.Sprintf("auto_https disable_redirects\n\thttps_port %d", proxyPort)
	if !https {
		portOption = fmt.Sprintf("auto_https off\n\thttp_port %d", proxyPort)
	}

	return fmt.Sprintf(`# LNS - Global Caddyfile
# Auto-generated by lns - do not edit manually
#
# This file imports all project-specific configurations.
# To reload after changes: lns reload
# Or: caddy reload --config %s --address %s
{
	admin %s
	%s
}

import %s/*.caddy
`, globalPath, adminAddr, adminAddr, portOption, caddyConfigDir)
}

func WriteProjectCaddyfile(project *models.Project) (string, error) {
	leases, err := devruntime.NewStore().Load()
	if err != nil {
		return "", err
	}
	return writeProjectCaddyfile(project, leases)
}

func writeProjectCaddyfile(project *models.Project, leases []devruntime.Lease) (string, error) {
	caddyConfigDir := config.GetCaddyConfigDir()

	if err := os.MkdirAll(caddyConfigDir, 0755); err != nil {
		return "", err
	}

	configPath := ProjectCaddyfilePath(project.Name)

	settings, err := config.LoadSettings()
	if err != nil {
		return "", err
	}

	occupied := make(map[string]bool, len(leases))
	for _, lease := range leases {
		occupied[strings.ToLower(lease.Hostname)] = true
	}
	filtered := *project
	filtered.Services = make([]models.Service, 0, len(project.Services))
	for _, service := range project.Services {
		if !occupied[strings.ToLower(project.GetServiceHostname(service))] {
			filtered.Services = append(filtered.Services, service)
		}
	}
	content := generateProjectCaddyfile(&filtered, settings.HTTPPort, settings.HTTPS, UpstreamModeHost)
	if err := state.WriteFileAtomic(configPath, []byte(content), 0644); err != nil {
		return "", err
	}

	return configPath, nil
}

func WriteGlobalCaddyfile() (string, error) {
	globalPath := config.GetGlobalCaddyfilePath()

	if err := os.MkdirAll(filepath.Dir(globalPath), 0755); err != nil {
		return "", err
	}

	settings, err := config.LoadSettings()
	if err != nil {
		return "", err
	}

	content := generateGlobalCaddyfile(settings.HTTPPort, settings.AdminAddr, settings.HTTPS)
	if err := state.WriteFileAtomic(globalPath, []byte(content), 0644); err != nil {
		return "", err
	}

	return globalPath, nil
}

func RemoveProjectCaddyfile(projectName string) error {
	configPath := ProjectCaddyfilePath(projectName)

	err := os.Remove(configPath)
	if os.IsNotExist(err) {
		return nil
	}
	return err
}

func projectConfigBasename(projectName string) string {
	name := strings.ToLower(strings.TrimSpace(projectName))
	if name == "" {
		return "project"
	}

	var b strings.Builder
	b.Grow(len(name))

	prevDash := false
	for _, r := range name {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			b.WriteRune(r)
			prevDash = false
		case r == '-' || r == '_':
			b.WriteRune(r)
			prevDash = false
		default:
			if !prevDash {
				b.WriteByte('-')
				prevDash = true
			}
		}
	}

	s := strings.Trim(b.String(), "-")
	if s == "" {
		return "project"
	}
	if runes := []rune(s); len(runes) > 120 {
		return string(runes[:120])
	}
	return s
}

func ProjectCaddyfilePath(projectName string) string {
	return filepath.Join(config.GetCaddyConfigDir(), projectConfigBasename(projectName)+".caddy")
}

func RegenerateAllCaddyfiles() ([]string, error) {
	mgr, err := registry.NewManager()
	if err != nil {
		return nil, err
	}

	leases, err := devruntime.NewStore().Load()
	if err != nil {
		return nil, err
	}

	var paths []string

	globalPath, err := WriteGlobalCaddyfile()
	if err != nil {
		return nil, err
	}
	paths = append(paths, globalPath)

	runtimePath, err := WriteRuntimeCaddyfile(leases)
	if err != nil {
		return paths, err
	}
	paths = append(paths, runtimePath)

	for _, project := range mgr.Registry.Projects {
		path, err := writeProjectCaddyfile(&project, leases)
		if err != nil {
			return paths, err
		}
		paths = append(paths, path)
	}

	return paths, nil
}

func GenerateRuntimeCaddyfile(leases []devruntime.Lease, proxyPort int, https bool) string {
	var sb strings.Builder
	sb.WriteString("# Active development processes\n\n")
	for _, lease := range leases {
		project := models.Project{Name: lease.Project}
		service := models.Service{
			Name:     lease.Service,
			Port:     lease.Port,
			Hostname: lease.Hostname,
			Profile:  lease.Profile,
			Status:   models.StatusResolved,
		}
		project.Services = []models.Service{service}
		sb.WriteString(generateServiceBlock(&project, &project.Services[0], proxyPort, https, UpstreamModeHost))
		sb.WriteString("\n\n")
	}
	return sb.String()
}

func WriteRuntimeCaddyfile(leases []devruntime.Lease) (string, error) {
	settings, err := config.LoadSettings()
	if err != nil {
		return "", err
	}
	path := config.GetRuntimeCaddyfilePath()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return "", err
	}
	if err := state.WriteFileAtomic(path, []byte(GenerateRuntimeCaddyfile(leases, settings.HTTPPort, settings.HTTPS)), 0644); err != nil {
		return "", err
	}
	return path, nil
}

func GenerateStandaloneCaddyfile(project *models.Project, port int, upstreamMode UpstreamMode) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf(`# Standalone Caddyfile for %s
# Generated by lns
#
# Usage:
#   caddy run --config Caddyfile
#   OR add to docker-compose.yml

{
	auto_https off
	http_port %d
}

`, project.Name, port))

	for i := range project.Services {
		sb.WriteString(generateServiceBlock(project, &project.Services[i], port, false, upstreamMode))
		sb.WriteString("\n\n")
	}

	return sb.String()
}

func getUpstream(service *models.Service, mode UpstreamMode) string {
	if mode == UpstreamModeDockerNetwork {
		return service.GetDockerUpstream()
	}
	return service.GetUpstream()
}

func GenerateDockerComposeSnippet(project *models.Project, httpPort int) string {
	network := project.DockerNetwork
	if network == "" {
		network = "app_network"
	}

	var dependsOn strings.Builder
	for _, service := range project.Services {
		if service.Docker && service.ContainerName != "" {
			dependsOn.WriteString(fmt.Sprintf("      - %s\n", service.ContainerName))
		}
	}

	deps := dependsOn.String()
	if deps == "" {
		deps = "      []"
	} else {
		deps = strings.TrimSuffix(deps, "\n")
	}

	return fmt.Sprintf(`# Add this to your docker-compose.yml services section
caddy:
    image: caddy:2-alpine
    ports:
        - "%d:%d"
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
        - %s
    restart: unless-stopped
    depends_on:
%s
`, httpPort, httpPort, network, deps)
}
